### ISSUE TITLE
Add methods to get primary key metadata for given table(s)

### ISSUE THREAD

**Issue by jimsmart** [jimsmart/schema#1]
Suggested by @gnewton — see https://github.com/golang/go/issues/7408#issuecomment-436639749

> Looking at your API your schema.Table(..) does not expose a Table.PrimaryKeys(), which I would certainly find useful (similar to https://docs.oracle.com/javase/6/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys(java.lang.String,%20java.lang.String,%20java.lang.String). I would also find a Table.ForeignKeys() to be useful. 👍 :-) Thanks.

**Comment by leopku** [comment]
Desire this feature.
Hope it can be done.

**Comment by jimsmart** [comment]
This has been added in the newly released v0.0.7
